name: Build AI Job Recommendations Backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read


jobs:
  build:
    if: !contains(github.event.head_commit.message, 'norun')
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Checkout AI-Model-Ultimate-Deploy Repository
        uses: actions/checkout@v4
        with:
          repository: https://github.com/rforberger/AI-model-ultimate-deploy.git
          path: './AI-Model-Ultimate-Deploy'
