name: Build AI Job Recommendations Backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read


jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Checkout AI-Model-Ultimate-Deploy Repository
        uses: actions/checkout@v4
        with:
          repository: rforberger/AI-model-ultimate-deploy
          path: './AI-Model-Ultimate-Deploy'
          token: ${{ secrets.GH_TOKEN }}
          ref: 'Extended_View_2025_03'

