name: Build AI Job Recommendations Backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  REGISTRY_AUTH_FILE: "/tmp/auth.json"

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Checkout AI-Model-Ultimate-Deploy Repository
        uses: actions/checkout@v4
        with:
          repository: rforberger/AI-model-ultimate-deploy
          path: './AI-Model-Ultimate-Deploy'
          token: ${{ secrets.GH_TOKEN }}
          ref: 'Extended_View_2025_03'

      - uses: actions/setup-python@v5
        #with:
        #  python-version: '3.12.9'

      - name: Install Python-venv
        run: |
          sudo apt update
          sudo apt install -y python3.11-venv

      - name: Create Python Virtual Env
        run: |
          python3 -m venv .

      - name: Install Python pip
        run: |
          sudo apt install -y python3-pip

      - name: Install Python dependencies
        run: |
          . bin/activate
          pip3 install -r requirements.txt
          poetry install --no-root

      - name: Run deployeee.py
        run: |
          . bin/activate
          podman login -u "${{ vars.DOCKERIO_USERNAME }}" -p "${{ secrets.DOCKERIO_PASSWORD }}" docker.io
          ./deployeee.py
